# Site settings
name: T Banerjee
title: T Banerjee | Computer Vision and Inverse Graphics

# Short bio or description
description: Research assistant at Princeton Computational Imaging Lab working on explainable 3D perception via inverse generation

# URL of your avatar or profile pic
avatar: images/avatar.jpeg

# Social links
footer-links:
  email: tb21@princeton.edu
  github: tanushreebanerjee
  instagram: tanushreebanerjee1
  linkedin: tanushreebanerjee1

# Your website URL
url: "https://tanushreebanerjee.github.io"

# Permalink structure
permalink: /:title/

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

# Set the Sass partials directory
sass:
  style: :compressed

# Use plugins
plugins:
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - command.txt
  - todo.txt
  - _temp/
  - _make_thumbnails.sh
  - make_thumbnails.py
