# Site settings
name: Tanushree Banerjee
title: Tanushree Banerjee | Researcher in Explainable 3D Perception

# Short bio or description (displayed in the header)
description: Research assistant at Princeton Computational Imaging Lab working on explainable 3D perception via inverse generation

# URL of your avatar or profile pic
avatar: images/avatar.jpeg

# Social links
footer-links:
  email: tb21@princeton.edu
  github: tanushreebanerjee
  instagram: tanushreebanerjee1
  linkedin: tanushree-banerjee-2001

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: G-E00L9PT3V9

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: "https://tanushreebanerjee.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

# Permalink structure
permalink: /:title/

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - command.txt
  - todo.txt
  - _temp/index.html
  - _temp/
  - _make_thumbnails.sh
  - make_thumbnails.py
