# Site settings
name: T Banerjee
title: T Banerjee

# Short bio or description
description: Research assistant at Princeton Computational Imaging Lab, incoming PhD student at University of Maryland working on explainable 3D perception via inverse generation

# Long description for SEO
long_description: >-
  Tanushree Banerjee is a researcher in computer vision and graphics focusing on explainable 3D perception
  via inverse generation. Currently a research assistant at Princeton University's Computational Imaging Lab
  working with Prof. Felix Heide, she will join the University of Maryland as a PhD student in Fall 2025.
  Her research interests include computer vision, computer graphics, machine learning, and optimization.

# Academic information
academic_status: Research Assistant & Incoming PhD Student
institution: Princeton University & University of Maryland
department: Computer Science Department
research_areas: [Computer Vision, Computer Graphics, Machine Learning, Optimization]

# URL of your avatar or profile pic
avatar: images/avatar.jpeg

# Social links
footer-links:
  email: tb21@princeton.edu
  github: tanushreebanerjee
  linkedin: tanushreebanerjee1
  scholar: 9gamKaAAAAAJ

# Your website URL
url: "https://tanushreebanerjee.github.io"
baseurl: ""

# Permalink structure
permalink: /:title/

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

# Set the Sass partials directory
sass:
  style: :compressed

# Use plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - command.txt
  - todo.txt
  - _temp/
  - _make_thumbnails.sh
  - make_thumbnails.py
  - .gitignore
